### ISSUE TITLE
Questions about the plane position embedding

### ISSUE THREAD

**Issue by come880412** [KVishnuVardhanR/M3T#3]
Hello,

First of all, I would like to express my gratitude for your excellent work! I have noticed in the section on position and plane embedding (refer to Fig.3(d)) that in your implementation, the same embedding appears to be used. However, in the original paper, the author applied different plane position embeddings for various plane tokens. Could you please clarify if I have misunderstood this aspect? Thank you for taking the time to address my query!
``` python3
# Ppos ∈ R((3S+4)×d)
self.plane = nn.Parameter(torch.randn(total_tokens + 4, emb_size))
```

**Comment by KVishnuVardhanR** [comment]
Hi,

Thank you for reaching out, the plane and positional embeddings in my implementation are not same, However, they are of same size and syntactically identical. But the purpose of positional embedding is to retain position information during the course of training and plane embeddings to give information indicating which plane these tokens belong to, during the course of training.

The author did not use various plane tokens (**refer to section 3.5**), In the Fig.3(d), the author presents few tokens belong to a particular plane and numbering each token sequentially to indicate the position of the tokens. However, this is just to give us an idea and intuition that the model learns and identifies these positions and planes. 

I have updated my readme, its not **# Ppos** it is **#Ppln**
>```
> # Ppln ∈ R((3S+4)×d)
> self.plane = nn.Parameter(torch.randn(total_tokens + 4, emb_size))

Thank you!

**Comment by come880412** [comment]
Hello,

Thank you for your prompt response and for clarifying my question. It seems that in your implementation, while each plane has a distinct embedding, the Ppos and Ppln embeddings essentially perform the same function, as they are all sampled differently across plane representations. This raises an interesting point about the potential redundancy of these embeddings, suggesting that one could be removed without significantly affecting performance, especially considering that Ppln does not seem to learn plane-specific information. The pseudo-code of my thought  is as follows:
``` python
def __init__(self,):
    # Ppln ∈ R((3S+4)×d)
    self.Cor_plane_pos = nn.Parameter(torch.randn(1, emb_size))
    self.Sag_plane_pos = nn.Parameter(torch.randn(1, emb_size))
    self.Ax_plane_pos = nn.Parameter(torch.randn(1, emb_size))
def forward(self, x_in):
    x[:, :130] += self.Cor_plane_pos 
    x[:, 130:259] += self.Sag_plane_pos 
    x[:, 259:] += self.Ax_plane_pos 
``` 
To this end, the Ppln embeddings can learn the plane-specific information since the different plane representations share the same embeddings.

Looking forward to your insights on the proposed code changes.

**Comment by KVishnuVardhanR** [comment]
Hi,

Your proposed approach to use separate plane embeddings for different segments of the input tensor is indeed a way to inject plane-specific information into the model. This method can help the model distinguish between different planes if they have unique features that are relevant to the task.

**Comment by come880412** [comment]
Hi,

I've seen that you modified your implementation to the plane-specific embeddings. However, from the current implementation, although you split the plane embeddings into three categories (i.e., Coronal, Sagittal, Axial), they are also different across the same type of plane. This is similar to the original implementation. To obtain the plane-specific information, I think the implementation should be like this:
```python
def __init__(self,):
    # Ppln ∈ R((3S+4)×d)
    self.Cor_plane_pos = nn.Parameter(torch.randn(1, emb_size))
    self.Sag_plane_pos = nn.Parameter(torch.randn(1, emb_size))
    self.Ax_plane_pos = nn.Parameter(torch.randn(1, emb_size))
```
To this end, the same type of planes can be shared with the same embeddings to enforce the model learn the plane-specific information
