### ISSUE TITLE
Complete code of the project

### ISSUE THREAD

**Issue by hczyni** [KVishnuVardhanR/M3T#4]
Hello dear AI engineer, I like the paper very much and am eager to get the complete code of the project, not just the network part. Thank you!

**Comment by KVishnuVardhanR** [comment]
I'm sorry, as I'm not the author who worked on this research, I don't have access to the complete code of the project. The authors of this research are from the Yonsei University, please try reaching out to them!

Thank you

**Comment by hczyni** [comment]
> 很抱歉，由于我不是从事这项研究的作者，因此我无法访问该项目的完整代码。这项研究的作者来自延世大学，请尝试与他们联系！
> 
> 谢谢



> 很抱歉，由于我不是从事这项研究的作者，因此我无法访问该项目的完整代码。这项研究的作者来自延世大学，请尝试与他们联系！
> 
> 谢谢

Dear AI engineer, do you have code for 3D classification? I don't have the classification code that can call M3T network, can you provide it? thank you.

**Comment by KVishnuVardhanR** [comment]
Yes, you check out the M3T.py file in the repo. It's the complete classification code that you can use to call M3T network.

**Comment by hczyni** [comment]
> 是的，您可以在存储库中签出 M3T.py 文件。这是可用于调用 M3T 网络的完整分类代码。

Dear AI developer, I received the M3T network you sent, but I have no code to call the M3T network you shared! Can you help me? Thank you!

**Comment by KVishnuVardhanR** [comment]
Hi,

you can copy the code from the M3T.py file from the repo and call the M3T network using the following command:
`model = M3T()`
