### ISSUE TITLE
Could you please provide the pre-trained model weights?

### ISSUE THREAD

**Issue by Xiaotong-Zhu** [KVishnuVardhanR/M3T#8]
Thank you for your excellent work on the M3T model! It is an impressive contribution to the field. I am currently working on a project that could greatly benefit from using the M3T model. I noticed that the repository does not include pre-trained weights for the model. Could you please provide the pre-trained model weights? Having access to the pre-trained model would be incredibly helpful for my research and application.

**Comment by KVishnuVardhanR** [comment]
Unfortunately, I'm not an author who worked on this research. So I do not have any pre trained weights for the M3T model.
