### ISSUE TITLE
Why do my results with torchsummary and torchinfo differ from your test results？There is a significant gap in the demand for memory.

### ISSUE THREAD

**Issue by sharll** [KVishnuVardhanR/M3T#9]
![044a0b2f9bacb651757a4a067608fb39](https://github.com/user-attachments/assets/8c0a3ffc-cd2a-4148-a6cb-2f3ef4ced172)
![2def6507e767e9a6a944847cb77df5fb](https://github.com/user-attachments/assets/4e336e5b-20dd-4701-b898-ba18e452002d)
The first picture is torch info and the second is torchsummary.

**Comment by KVishnuVardhanR** [comment]
Hi,

Thank you for reaching out. Please refer to the following link:
https://colab.research.google.com/drive/1r_ylzwsxbOKBYkNv3buZ2S14vnz69-NW?usp=sharing
